In [4]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

from stat_utils import statistical_tests_step1
from utils import plot_dataframe

In [2]:
df = pd.read_csv('artifacts/train_data.csv')
test = pd.read_csv('artifacts/test_data.csv')
df.head()

,발급회원번호,남녀구분코드,연령,VIP등급코드,최상위카드등급코드,회원여부_이용가능,회원여부_이용가능_CA,회원여부_이용가능_카드론,소지여부_신용,회원여부_연체,이용거절여부_카드론,이용금액_R3M_신용,이용금액_R3M_체크,이용금액_R3M_신용_가족,이용금액_R3M_체크_가족,보유여부_해외겸용_본인,이용가능여부_해외겸용_본인,이용여부_3M_해외겸용_본인,거주시도명,직장시도명,가입통신회사코드,Life_Stage,최종카드발급경과월,최초한도금액,카드이용한도금액,CA한도금액,일시상환론한도금액,월상환론한도금액,CA이자율_할인전,CL이자율_할인전,RV일시불이자율_할인전,RV현금서비스이자율_할인전,자발한도감액횟수_R12M,자발한도감액금액_R12M,강제한도감액횟수_R12M,강제한도감액금액_R12M,한도증액횟수_R12M,한도증액금액_R12M,상향가능한도금액,상향가능CA한도금액,월상환론상향가능한도금액,RV신청일자,RV약정청구율,RV최소결제비율,RV전환가능여부,일시불ONLY전환가능여부,시장단기연체여부_R6M,시장단기연체여부_R3M,시장연체상환여부_R6M,시장연체상환여부_R3M,한도심사요청건수,한도요청거절건수,한도심사요청후경과월,한도심사거절후경과월,최종이용일자_기본,최종이용일자_신판,최종이용일자_CA,최종이용일자_카드론,최종이용일자_체크,최종이용일자_일시불,최종이용일자_할부,이용건수_신용_B0M,이용건수_신판_B0M,이용건수_일시불_B0M,이용건수_할부_B0M,이용건수_할부_유이자_B0M,이용건수_할부_무이자_B0M,이용건수_부분무이자_B0M,이용건수_CA_B0M,이용건수_체크_B0M,이용건수_카드론_B0M,이용금액_신용_B0M,이용금액_신판_B0M,이용금액_일시불_B0M,이용금액_할부_B0M,이용금액_할부_유이자_B0M,이용금액_할부_무이자_B0M,이용금액_부분무이자_B0M,이용금액_CA_B0M,이용금액_체크_B0M,이용금액_카드론_B0M,이용금액_업종기준,이용금액_쇼핑,이용금액_요식,이용금액_교통,이용금액_의료,이용금액_납부,이용금액_교육,이용금액_여유생활,이용금액_사교활동,이용금액_일상생활,이용금액_해외,RP금액_B0M,할부건수_3M_R12M,할부건수_6M_R12M,할부건수_12M_R12M,할부건수_14M_R12M,할부금액_3M_R12M,할부금액_6M_R12M,할부금액_12M_R12M,할부금액_14M_R12M,이용횟수_연체_R6M,이용금액_연체_R6M,이용횟수_연체_R3M,이용금액_연체_R3M,이용횟수_연체_B0M,이용금액_연체_B0M,건수_할부전환_R6M,건수_할부전환_R3M,금액_할부전환_R6M,금액_할부전환_R3M,신청건수_ATM_CA_B0,신청건수_ATM_CL_B0,신청건수_ATM_CA_R6M,신청건수_ATM_CL_R6M,승인거절건수_B0M,승인거절건수_한도초과_B0M,승인거절건수_BL_B0M,승인거절건수_입력오류_B0M,승인거절건수_기타_B0M,정상청구원금_B0M,선입금원금_B0M,정상입금원금_B0M,연체입금원금_B0M,잔액_B0M,잔액_일시불_B0M,잔액_할부_B0M,잔액_현금서비스_B0M,잔액_리볼빙일시불이월_B0M,잔액_리볼빙CA이월_B0M,잔액_카드론_B0M,월중평잔_일시불_B0M,월중평잔_할부_B0M,월중평잔_CA_B0M,카드론잔액_최종경과월,연체일자_B0M,연체잔액_B0M,연체잔액_일시불_B0M,연체잔액_할부_B0M,연체잔액_현금서비스_B0M,연체잔액_카드론_B0M,연체잔액_대환론_B0M,잔액_현금서비스_B1M,잔액_현금서비스_B2M,잔액_카드론_B1M,잔액_카드론_B2M,잔액_카드론_B3M,잔액_카드론_B4M,잔액_카드론_B5M,잔액_할부_B1M,잔액_할부_B2M,잔액_일시불_B1M,잔액_일시불_B2M,연체일수_B1M,연체일수_B2M,연체원금_B1M,연체원금_B2M,연체일수_최근,연체원금_최근,최종연체회차,매각잔액_B1M,최종연체개월수_R15M,RV_평균잔액_R12M,RV_최대잔액_R12M,RV_평균잔액_R6M,RV_최대잔액_R6M,RV_평균잔액_R3M,RV_최대잔액_R3M,RV잔액이월횟수_R6M,RV잔액이월횟수_R3M,잔액_할부_유이자_B0M,잔액_할부_무이자_B0M,잔액_할부_해외_B0M,연체잔액_일시불_해외_B0M,연체잔액_RV일시불_B0M,연체잔액_RV일시불_해외_B0M,연체잔액_할부_해외_B0M,연체잔액_CA_B0M,연체잔액_CA_해외_B0M,월중평잔,월중평잔_일시불,월중평잔_RV일시불,월중평잔_할부,월중평잔_CA,월중평잔_카드론,평잔_3M,평잔_일시불_3M,평잔_일시불_해외_3M,평잔_RV일시불_3M,평잔_RV일시불_해외_3M,평잔_할부_3M,평잔_할부_해외_3M,평잔_CA_3M,평잔_CA_해외_3M,평잔_카드론_3M,상담건수_B0M,불만제기건수_B0M,인입횟수_ARS_B0M,방문횟수_앱_B0M,방문횟수_PC_B0M,IB문의건수_카드발급_B0M,IB문의건수_BL_B0M,IB문의건수_분실도난_B0M,IB문의건수_CA_B0M,IB문의건수_CL_RV_B0M,IB문의건수_CS_B0M,컨택건수_리볼빙_TM_B0M,컨택건수_리볼빙_LMS_B0M,컨택건수_리볼빙_EM_B0M,증감율_이용금액_신용_전월,증감율_이용금액_신판_전월,증감율_이용금액_일시불_전월,증감율_이용금액_할부_전월,증감율_이용금액_CA_전월,증감율_이용금액_체크_전월,증감율_이용금액_카드론_전월,잔액_신판평균한도소진율_r6m,잔액_신판최대한도소진율_r6m,잔액_신판평균한도소진율_r3m,잔액_신판최대한도소진율_r3m,잔액_신판ca평균한도소진율_r6m,잔액_신판ca최대한도소진율_r6m,잔액_신판ca평균한도소진율_r3m,잔액_신판ca최대한도소진율_r3m,변동률_잔액_B1M,변동률_잔액_일시불_B1M,잔액_리볼빙일시불이월_target
0,SYN_108,1,40대,07,_,1,1,0,1,0,0,1420593,164442,0,0,1,1,1,부산,부산,NaN,4.자녀성장기(1),33,0,4209755,1207351,0,0,22.998256,18.565066,18.683562,21.222902,0,0,0,0,0,0,0,0,0,20160724.0,20.912946,10.0,N,0,0,0,0,0,0,0,3,3,20181018,20181006,20181018,20170311,20181005,20181006,20171216,7,5,5,0,0,0,0,2,8,0,1371569,530723,530723,0,0,0,0,840846,198649,0,985459,0,0,0,0,0,0,0,148793,39203,187222,0,0,0,0,0,0,0,339282,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1046151,673095,0,373056,6148994,2292379,0,1188442,1512611,0,1155562,2541927,0,1011422,0,NaN,0,0,0,0,0,0,1234810,1194247,1047618,1081465,1122353,1226792,1188291,0,70636,2866610,2698949,-99999999,-99999999,0,0,-99999999,0,-9999,0,0,2249140,2964268,1739689,2056324,1770436,2056324,6,3,0,0,0,0,0,0,0,0,0,3204525,2431626,3709992,0,998823,900550,3682014,2245452,72888,4062640,58076,25883,0,1152834,0,541263,0,0,0,3,5,0,0,0,0,0,0,0,0,0,-0.239333,0.276597,0.276597,0.000000,-0.004083,0.035591,0.0,0.469525,0.591601,0.478563,0.535815,0.841197,1.051623,0.822354,0.966124,-0.024345,-0.047813,1540264
1,SYN_116,2,30대,06,_,1,0,0,1,0,0,0,1771551,0,0,1,1,1,대구,대구,KTF,4.자녀성장기(1),15,0,387324,0,0,0,22.998236,23.000000,19.892739,22.985478,0,0,4,204,1,147,0,0,0,20160714.0,20.492362,10.0,N,0,0,0,0,0,0,0,3,3,20180910,20180910,20180527,20151224,20181015,20180910,20180127,0,0,0,0,0,0,0,0,33,0,0,0,0,0,0,0,0,0,710684,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,275781,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2378072,1238731,0,0,1139341,0,0,1273831,0,804283,0,NaN,0,0,0,0,0,0,1099625,1128872,0,0,0,0,0,0,0,1419666,1559766,86,86,436871,535951,99,449847,-9999,0,3,1529022,2175153,1150024,1310550,1162321,1265760,6,3,0,0,0,0,0,0,0,0,0,1499231,1117335,1481292,0,868351,0,2607103,1190321,0,1464088,0,43060,0,722587,0,0,0,0,0,6,0,0,0,0,0,0,0,0,0,0,0.000052,0.000052,0.000052,0.000000,0.000000,0.000593,0.0,0.847372,0.939222,0.593439,0.619504,1.083753,1.287678,0.752603,0.834112,0.000000,0.000000,1073076
2,SYN_130,1,60대,07,_,1,1,0,1,0,0,678015,0,0,0,1,1,1,충남,충남,LGT,6.자녀출가기,38,0,8638043,2712135,0,0,22.057698,17.731908,17.257071,19.094705,0,0,0,0,0,0,0,0,0,20120128.0,19.625443,20.0,N,0,0,0,0,0,0,0,3,3,20181023,20181023,20181018,20171211,10101,20181023,20150709,9,7,7,0,0,0,0,2,0,0,848926,134267,134267,0,0,0,0,714659,0,0,934996,123104,0,154893,0,259685,0,0,92385,0,0,49592,10,4,0,0,1350458,1061189,0,0,0,0,0,0,0,0,0,0,0,0,0,0,9,0,0,0,0,0,0,707327,707327,0,0,10621291,3020335,371042,916661,1936044,2631417,1745792,2887384,185617,698460,0,NaN,0,0,0,0,0,0,883489,851215,1684909,1712524,1729359,1958451,2402622,191333,230682,3338609,3599158,-99999999,-99999999,0,0,-99999999,0,-9999,0,0,3803153,3772276,2737139,2933212,2796448,2933212,6,3,244328,126714,0,0,0,0,0,0,0,10129764,2735060,3292995,183344,676758,1549500,11103541,2736418,0,3947971,0,205780,0,680114,0,1381643,0,0,2,0,0,0,0,0,0,0,0,0,0,0,-0.237094,0.287526,0.227215,-0.021636,0.030243,0.000000,0.0,0.746399,0.868317,0.717361,0.805100,0.971977,1.148749,0.950426,1.079163,-0.049765,0.010522,1929447
3,SYN_214,1,40대,07,_,1,1,0,1,0,0,1747512,0,0,0,1,1,1,전북,전북,SKT,4.자녀성장기(1),12,0,8792092,3072554,0,0,19.061550,17.328939,16.254520,18.856106,0,0,0,0,1,181,794,282,0,20160726.0,100.000000,20.0,Z,1,0,0,0,0,0,0,3,3,20181017,20181005,20181017,20171219,10101,20181005,20180515,10,8,8,0,0,0,0,2,0,0,1092614,336233,336233,0,0,0,0,756381,0,0,1199629,261444,34812,216128,46056,169064,0,119953,287458,0,0,36051,4,0,0,0,1072490,0,0,0,2,376180,0,0,0,0,0,0,0,0,3,0,8,0,0,0,0,0,0,1196665,0,652399,544266,10380384,819989,0,912991,894886,0,7752518,1302398,0,709530,0,NaN,0,0,0,0,0,0,847714,871530,9201681,9122325,8969051,8746611,10952923,0,0,949270,973286,0,0,0,0,-99999999,0,0,0,0,317252,890150,462790,809432,521198,809432,6,3,0,0,0,0,0,0,0,0,0,14950789,1158498,1621869,0,677342,9067277,21673218,1949992,0,2039534,0,32262,0,723535,0,12338518,0,0,0,3,0,0,0,0,0,0,0,0,0,0,-0.266499,0.241726,0.241726,0.000000,0.037478,0.000000,0.0,0.022702,0.083831,0.000000,0.006408,0.257389,0.392657,0.212049,0.291900,0.079660,0.062261,928248
4,SYN_227,1,50대,07,_,1,1,0,1,0,0,1852445,0,0,0,1,1,0,인천,인천,SKT,5.자녀성장기(2),4,0,5140724,1568296,0,0,22.996741,18.412156,18.687616,21.312396,0,0,1,196,1,186,0,0,0,20160707.0,22.855123,20.0,N,0,0,0,0,0,0,0,3,3,20181031,20181031,20181023,20150524,10101,20181031,20180530,31,29,29,0,0,0,0,2,0,0,1823372,705905,705905,0,0,0,0,1117467,0,0,1065733,366689,0,172021,89200,228057,0,95775,454620,37950,0,24476,9,4,0,0,1096263,674332,0,0,1,158024,0,0,0,0,10,5,952914,477734,0,0,11,0,0,0,0,0,0,1754692,0,951455,803237,4914003,1644127,461325,1784148,1024403,0,0,2675803,206863,1938063,0,NaN,0,0,0,0,0,0,2029185,2007982,0,0,0,0,0,203157,217155,1668890,1520834,0,0,0,0,-99999999,0,0,0,2,831746,1541686,711455,1120249,826032,1120249,6,3,322735,138590,0,0,0,0,0,0,0,4915124,2077043,1470200,206157,1963178,0,4774080,2087627,0,1535652,0,241830,0,2527494,0,0,0,0,0,10,0,0,0,0,0,0,0,0,0,0,-0.229827,0.230818,0.230818,0.000000,-0.021921,0.000000,0.0,0.272367,0.296957,0.260692,0.275966,0.770058,0.859617,0.765867,0.837995,0.087329,0.032552,1005488

In [3]:
df.shape

(83403, 227)

- 얼마를 내기로 했는가?
- 그럼 현재의 금액은 얼마이고, 이 중 다음 달에 예정되어있는 금액은 얼마인가?
- 그래서 다음달에 냈는가?

In [6]:
tmp = df.loc[:, ['월중평잔_RV일시불', '이용금액_일시불_B0M', '이용금액_신용_B0M', '카드이용한도금액']]
tmp

       월중평잔_RV일시불  이용금액_일시불_B0M  이용금액_신용_B0M  카드이용한도금액
0         3709992        530723      1371569   4209755
1         1481292             0            0    387324
2         3292995        134267       848926   8638043
3         1621869        336233      1092614   8792092
4         1470200        705905      1823372   5140724
...           ...           ...          ...       ...
83398      473266        221909       221909   2999842
83399      719355        642836       642836   1916317
83400     4575879       1949057      1949057   8625526
83401     3014946       1136455      2803969  21465692
83402     1931991        728988      1824233   5172253

[83403 rows x 4 columns]

In [5]:
tmp = df.loc[:, ['잔액_리볼빙일시불이월_B0M', '잔액_리볼빙일시불이월_target', '월중평잔_RV일시불', 'RV약정청구율', 'RV최소결제비율', 'RV_평균잔액_R3M',
                 '연체잔액_RV일시불_B0M', '이용금액_연체_B0M', '이용금액_일시불_B0M', '이용금액_신용_B0M', '카드이용한도금액']]
tmp

,잔액_리볼빙일시불이월_B0M,잔액_리볼빙일시불이월_target,월중평잔_RV일시불,RV약정청구율,RV최소결제비율,RV_평균잔액_R3M,연체잔액_RV일시불_B0M,이용금액_연체_B0M,이용금액_일시불_B0M,이용금액_신용_B0M,카드이용한도금액
0,1512611,1540264,3709992,20.912946,10.0,1770436,0,0,530723,1371569,4209755
1,1139341,1073076,1481292,20.492362,10.0,1162321,0,0,0,0,387324
2,1936044,1929447,3292995,19.625443,20.0,2796448,0,0,134267,848926,8638043
3,894886,928248,1621869,100.000000,20.0,521198,0,0,336233,1092614,8792092
4,1024403,1005488,1470200,22.855123,20.0,826032,0,0,705905,1823372,5140724
...,...,...,...,...,...,...,...,...,...,...,...
83398,633546,0,473266,100.000000,20.0,250919,0,0,221909,221909,2999842
83399,928596,707413,719355,100.000000,20.0,410924,0,0,642836,642836,1916317
83400,1788408,1857104,4575879,21.295071,10.0,1911760,0,0,1949057,1949057,8625526
83401,1264595,1416558,3014946,22.551447,20.0,1430999,0,0,1136455,2803969,21465692
83402,900159,862931,1931991,100.000000,20.0,559654,0,0,728988,1824233,5172253